name: studentregister
description: "a simple registration form and store the value in Firebase database using android"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/login.png
  branding: assets/images/login.png
  color_dark: "#121212"
  image_dark: assets/images/login.png
  branding_dark: assets/images/login.png

  android_12:
    image: assets/images/login.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/login.png
    icon_background_color_dark: "#121212"

  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
